

model_name: "labhamlet/gramt-binaural-time"

defaults:
  - data: LA2019
  - model: deepfake_classifier
  - callbacks: experimento_test
  - logger: wandb 
  - trainer: gpu
  - paths: default
  - extras: default
  - hydra: default


  - experiment: null
  - hparams_search: null
  - optional local: default
  - debug: null
  - _self_

# task name, determines output directory path
task_name: "train"

tags: ["wavlm-large", "unfrozen_backbone", "per_layer_weights", "MLP", "mean_pooling"]

# set False to skip model training
train: True

# evaluate on test set, using best model weights achieved during training
# lightning chooses best weights based on the metric specified in checkpoint callback
test: True

# simply provide checkpoint path to resume training
ckpt_path: null

# seed for random number generators in pytorch, numpy and python.random
seed: 42

data:
  model_name: ${model_name}
  target_sample_rate: 32000

model:
  net:
    _target_: src.models.components.SLL_simple_classifier.GramtDeepFakeDynamicModel
    model_name: ${model_name}


wandb:
  project: "Deepfake-RADAR-Experiments"
  entity: "alexandreacff-federal-university-of-goi-s"
