
model_name: "facebook/wav2vec2-xls-r-300m"

defaults:
  - data: LA2019
  - model: deepfake_classifier
  - callbacks: experimento_test
  - logger: wandb # set logger here or use command line (e.g. `python train.py logger=tensorboard`)
  - trainer: gpu
  - paths: default
  - extras: default
  - hydra: default

  # experiment configs allow for version control of specific hyperparameters
  # e.g. best hyperparameters for given model and datamodule
  - experiment: null

  # config for hyperparameter optimization
  - hparams_search: null

  # optional local config for machine/user specific settings
  # it's optional since it doesn't need to exist and is excluded from version control
  - optional local: default

  # debugging config (enable through command line, e.g. `python train.py debug=default)
  - debug: null
  - _self_

# task name, determines output directory path
task_name: "eval"

# tags to help you identify your experiments
# you can overwrite this in experiment configs
# overwrite from command line with `python train.py tags="[first_tag, second_tag]"`
tags: ["testing"]

# set False to skip model training
train: False

# evaluate on test set, using best model weights achieved during training
# lightning chooses best weights based on the metric specified in checkpoint callback
test: True

# simply provide checkpoint path to resume training
ckpt_path: "/workspace/deepfake/deepfake/Deepfake-RADAR-Experiments/logs/train/runs/2026-04-28_04-43-48/checkpoints/epoch_002.ckpt"

# seed for random number generators in pytorch, numpy and python.random
seed: 42

data:
  model_name: ${model_name}

model:
  net:
    model_name: ${model_name}

wandb:
  project: "Deepfake-RADAR-Experiments"
  entity: "alexandreacff-federal-university-of-goi-s"
